[package]
name = "flame-wasm"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
async-trait = { workspace = true }

thiserror = "1.0"
bytes = { version = "1", features = ["serde"] }
lazy_static = "1.4"

[lib]
crate-type = ["cdylib"]