[workspace]

members = [
    "flmctl",
    "session_manager",
    "executor_manager",
    "rpc",
    "fping",
]


[workspace.dependencies]
tokio = { version = "1", features = ["full"] }
tonic = "0.8"
prost = "0.11"
env_logger = { version = "0.10" }

