[workspace]

members = [
    "common",
    "flmctl",
    "flmping",
    "session_manager",
    "executor_manager",
    "rpc",
]


[workspace.dependencies]
tokio = { version = "1", features = ["full"] }
tonic = "0.8"
prost = "0.11"
env_logger = { version = "0.10" }
log = { version = "0.4", features = ["std", "serde"] }

async-trait = "0.1"