apiVersion: skaffold/v4beta2
kind: Config
metadata:
  name: flame
build:
  tagPolicy:
    sha256: {}
  local:
    useBuildkit: true
    useDockerCLI: true
  insecureRegistries:
    - "registry.minikube"
  artifacts:
    - image: registry.minikube/flame-executor-manager
      docker:
        dockerfile: docker/Dockerfile.fem
      sync:
        infer:
          - "executor_manager"
    - image: registry.minikube/flame-session-manager
      docker:
        dockerfile: docker/Dockerfile.fsm
      sync:
        infer:
          - "session_manager"
    - image: registry.minikube/flame-console
      docker:
        dockerfile: docker/Dockerfile.console
      sync:
        infer:
          - "example"
          - "flmping"
          - "flmctl"
manifests:
  kustomize:
    paths:
      - installer

deploy:
  statusCheckDeadlineSeconds: 300
  tolerateFailuresUntilDeadline: true
  kubectl:
    defaultNamespace: flame-system
