[package]
name = "rpc"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
tokio = { workspace = true }

tonic = { workspace = true}
prost = "*"
prost-types = "*"
prost-build = "*"

[build-dependencies]
tonic-build = "0.8"