[package]
name = "flame-session-manager"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rpc = { path = "../rpc" }
tonic = { workspace = true }
env_logger = { workspace = true }
async-trait = "0.1"
thiserror = "1"

